package bell;

import java.util.Arrays;
import java.util.Random;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HPro1
 */
public class bell extends javax.swing.JFrame {
  Random rNumber = new Random();
    String[] words = {"money", "world", "dogs", "words", "crazy", "catchphrase", "beans", "place", "real", "president", "ferda", "jones", "computer", "keyboard", "red", "pink", "method", "orange", "blue"};
    String answer;
    String guess;
    char[] underlines;
    char[] guesses;
    char[] correctAnswer; // not required
    int wrongGuesses = 0;
    /**
     * Creates new form bell
     */
    public bell() {
        initComponents();
    }
 public void newGame() {
        answer = words[rNumber.nextInt(words.length)];
        System.out.println("Answer:" + answer);
        guesses = new char[answer.length() + 6]; // 6 is possible wrong answers
        Arrays.fill(guesses, 0, guesses.length-1, ' ');
        underlines = new char[answer.length()];
        Arrays.fill(underlines, 0, underlines.length, '_');
        wrongGuesses = 0;
        correctAnswer = new char[answer.length()];
        for (int i = 0; i < correctAnswer.length; i++) {
            correctAnswer[i] = answer.charAt(i);
        }
        updateDisplay();
    }
    
    public void updateDisplay() {
        updatePicture();
        String updateGuesses = "";
        for (int i = 0; i < guesses.length; i++) {
            updateGuesses = updateGuesses + guesses[i] + " ";
        }
        guessedLettersLabel.setText(updateGuesses);
        
        String updateUnderlines = "";
        for (int i = 0; i < underlines.length; i++) {
//            updateGuesses = updateUnderlines + underlines[i] + " ";
//          The Line above had the wrong variable to the left of the =
            updateUnderlines = updateUnderlines + underlines[i] + " ";
        }
        underlinesLabel.setText(updateUnderlines);
        resultsLabel.setText("");
    }
    
    public void updatePicture() {
        iconLabel.setIcon(new ImageIcon(getClass().getResource("hangman" + wrongGuesses + ".png")));
    }
    
    public static int arraySearch(char[] theArray, char key) {
        for (int index = 0; index < theArray.length; index++) {
            if (theArray[index] == key) {
                return index;  //We found it so return breaks out of the search method with location
            }
        }
        return -1;
    }
    
    public void results() {
        if (correctAnswer == underlines) {
            resultsLabel.setText("YOU WON!!");
        } else if (correctAnswer != underlines) {
            resultsLabel.setText("You lose. The word was " + answer);
        }
        if (wrongGuesses == 6) {
            resultsLabel.setText("You lost. The word was: " + answer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void clear() {
        guessTextField.setText("");
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        guessTextField = new javax.swing.JTextField();
        underlinesLabel = new javax.swing.JLabel();
        solveEntireWordButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        submitGuessButton = new javax.swing.JButton();
        guessedLettersLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bell/hangman0.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("STIX Two Text", 3, 48)); // NOI18N
        jLabel2.setText("Hangman");

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Guess:");

        guessTextField.setText(" ");

        underlinesLabel.setText("underlinesHere");

        solveEntireWordButton.setText("Solve Entire Word");
        solveEntireWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveEntireWordButtonActionPerformed(evt);
            }
        });

        resultsLabel.setText("resultsLabel");

        submitGuessButton.setText("Submit Guess");
        submitGuessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitGuessButtonActionPerformed(evt);
            }
        });

        guessedLettersLabel.setText("guesses label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(guessTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guessedLettersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(underlinesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(submitGuessButton)
                        .addGap(18, 18, 18)
                        .addComponent(newGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveEntireWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(iconLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guessedLettersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(underlinesLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(guessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitGuessButton)
                    .addComponent(newGameButton)
                    .addComponent(solveEntireWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
newGame();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void solveEntireWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveEntireWordButtonActionPerformed
         if (guessTextField.getText().equalsIgnoreCase(answer)) {
            resultsLabel.setText("You Win!!");
        } else if (guessTextField.getText().length() != correctAnswer.length) {
            resultsLabel.setText("You Lose. The word was: " + answer);
        }
       
    }//GEN-LAST:event_solveEntireWordButtonActionPerformed

    private void submitGuessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitGuessButtonActionPerformed
 if (guessTextField.getText().length() == 1) {
            for (int i = 0; i < correctAnswer.length; i++) {
                if (guessTextField.getText().charAt(0) == (correctAnswer[i])) {
                    //underlinesLabel.setText(guess);
                    underlines[i] = guessTextField.getText().charAt(0);
                    updateDisplay();
                    return;
                }                
            }
            guessedLettersLabel.setText(guess);
            wrongGuesses = wrongGuesses + 1;
        }
        clear();
        results();
        updateDisplay();
        updatePicture();
    }//GEN-LAST:event_submitGuessButtonActionPerformed
       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessTextField;
    private javax.swing.JLabel guessedLettersLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JButton solveEntireWordButton;
    private javax.swing.JButton submitGuessButton;
    private javax.swing.JLabel underlinesLabel;
    // End of variables declaration//GEN-END:variables
}
